### ISSUE TITLE
Node Disk Manager - panic: runtime error: index out of range

### ISSUE THREAD

**Issue by stewbernetes** [openebs/node-disk-manager#209]
**What happened**:
I attempted to upgrade our OpenEBS deployment from 0.8.0 to 0.8.1. Upon startup, all components launch successfully except the node-disk-manager.

Upon launch, I am getting the following error:

```
[entrypoint.sh] enabling core dump.
MAYA_APISERVER_SERVICE_SERVICE_HOST=100.66.61.117
SPARSE_FILE_DIR=/var/openebs/sparse
HOSTNAME=ip-10-10-182-200
MAYA_APISERVER_SERVICE_PORT_5656_TCP=tcp://100.66.61.117:5656
KUBERNETES_PORT_443_TCP_PORT=443
KUBERNETES_PORT=tcp://100.64.0.1:443
KUBERNETES_SERVICE_PORT=443
KUBERNETES_SERVICE_HOST=100.64.0.1
MAYA_APISERVER_SERVICE_SERVICE_PORT=5656
SPARSE_FILE_COUNT=1
SPARSE_FILE_SIZE=10737418240
MAYA_APISERVER_SERVICE_PORT=tcp://100.66.61.117:5656
PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
PWD=/
MAYA_APISERVER_SERVICE_PORT_5656_TCP_PROTO=tcp
MAYA_APISERVER_SERVICE_SERVICE_PORT_API=5656
SHLVL=1
HOME=/root
KUBERNETES_PORT_443_TCP_PROTO=tcp
KUBERNETES_SERVICE_PORT_HTTPS=443
MAYA_APISERVER_SERVICE_PORT_5656_TCP_ADDR=100.66.61.117
NODE_NAME=ip-10-10-182-200.ec2.internal
MAYA_APISERVER_SERVICE_PORT_5656_TCP_PORT=5656
KUBERNETES_PORT_443_TCP_ADDR=100.64.0.1
KUBERNETES_PORT_443_TCP=tcp://100.64.0.1:443
_=/usr/bin/env
GOTRACEBACK=crash
[entrypoint.sh] launching ndm process.
I0226 15:29:53.757555       8 controller.go:170] Disk CRD is available
I0226 15:29:53.757634       8 filter.go:58] registering filters
I0226 15:29:53.757647       8 filter.go:66] configured os disk exclude filter : state enable
I0226 15:29:53.757807       8 filter.go:66] configured vendor filter : state enable
I0226 15:29:53.757819       8 filter.go:66] configured path filter : state enable
I0226 15:29:53.757831       8 probe.go:61] registering probes
I0226 15:29:53.757842       8 probe.go:83] configured seachest probe : state enable
I0226 15:29:53.757855       8 probe.go:83] configured smart probe : state enable
I0226 15:29:53.757923       8 probe.go:83] configured udev probe : state enable
I0226 15:29:53.757959       8 udevprobe.go:197] starting udev probe listener
I0226 15:29:53.758493       8 udevprobe.go:154] Partition Data for disk-597f921a5f9ad55ad73e1dfd34ea02d5 : [{21686148-6449-6e6f-744e-656564454649 None}]
I0226 15:29:53.758623       8 udevprobe.go:154] Partition Data for disk-d6970214e6015f64495895c5a04dbe75 : [{0fc63daf-8483-4772-8e79-3d69d8477de4 ext4}]
panic: runtime error: index out of range
 goroutine 1 [running]:
github.com/openebs/node-disk-manager/cmd/probe.(*udevProbe).scan(0xc4204cd620, 0xc4204cd620, 0xc4204ccf20)
    /home/travis/gopath/src/github.com/openebs/node-disk-manager/cmd/probe/udevprobe.go:165 +0xacf
```

**What you expected to happen**:
I expect node-disk-manager to start.

**How to reproduce it (as minimally and precisely as possible)**:

I am using the generic openebs-operator deployment manifest. I am able to consistently reproduce the issue by simply applying the manifest.

**Anything else we need to know?**:

Looking at the source for udevprobe.go, this line:
https://github.com/openebs/node-disk-manager/blob/0daf87bbce486190759cff636d934531dc9875d6/cmd/ndm_daemonset/probe/udevprobe.go#L165

Appears to have a hard coded value. Is this intended? The index out of bounds appears to originate here.

**Comment by kmova** [comment]
Thanks @stewbernetes. That hard coded line should not be there. 

Fixed by https://github.com/openebs/node-disk-manager/pull/210

**Comment by stewbernetes** [comment]
@kmova Version 0.3.1 has addressed the issue:
```
I0226 17:41:22.055069       8 probe.go:107] details filled by seachest probe
E0226 17:41:22.055111       8 smartprobe.go:100] map[errorCheckingConditions:the device type is not supported yet, device type: "unknown"]
I0226 17:41:22.055122       8 probe.go:107] details filled by smart probe
E0226 17:41:22.055161       8 capacityprobe.go:96] unable to read sector sizeopen /sys/dev/block/259:1/queue/hw_sector_size: no such file or directory
I0226 17:41:22.055169       8 probe.go:107] details filled by capacity probe
I0226 17:41:22.055177       8 eventhandler.go:55] processed data for disk-597f921a5f9ad55ad73e1dfd34ea02d5
I0226 17:41:22.055185       8 eventhandler.go:60] Skipping partition of already excluded disk disk-597f921a5f9ad55ad73e1dfd34ea02d5
I0226 17:41:22.055189       8 eventhandler.go:49] processing details for disk-d6970214e6015f64495895c5a04dbe75
I0226 17:41:22.055292       8 probe.go:107] details filled by udev probe
I0226 17:41:22.055406       8 seachestprobe.go:116] Disk: /dev/nvme0n1p2 Model: filled by seachest.
I0226 17:41:22.055416       8 seachestprobe.go:126] Disk: /dev/nvme0n1p2 Capacity:0 filled by seachest.
I0226 17:41:22.055422       8 seachestprobe.go:136] Disk: /dev/nvme0n1p2 Vendor: filled by seachest.
I0226 17:41:22.055430       8 seachestprobe.go:141] Disk: /dev/nvme0n1p2 FirmwareRevision: filled by seachest.
I0226 17:41:22.055436       8 seachestprobe.go:146] Disk: /dev/nvme0n1p2 LogicalSectorSize:0 filled by seachest.
I0226 17:41:22.055444       8 seachestprobe.go:151] Disk: /dev/nvme0n1p2 PhysicalSectorSize:0 filled by seachest.
I0226 17:41:22.055449       8 seachestprobe.go:156] Disk: /dev/nvme0n1p2 RotationRate:0 filled by seachest.
I0226 17:41:22.055455       8 seachestprobe.go:161] Disk: /dev/nvme0n1p2 DriveType:Not Available filled by seachest.
I0226 17:41:22.055461       8 seachestprobe.go:166] Disk: /dev/nvme0n1p2 TotalBytesRead:0 filled by seachest.
I0226 17:41:22.055470       8 seachestprobe.go:171] Disk: /dev/nvme0n1p2 TotalBytesWritten:0 filled by seachest.
I0226 17:41:22.055475       8 seachestprobe.go:176] Disk: /dev/nvme0n1p2 DeviceUtilizationRate:%!d(float64=0) filled by seachest.
I0226 17:41:22.055483       8 seachestprobe.go:181] Disk: /dev/nvme0n1p2 PercentEnduranceUsed:%!d(float64=0) filled by seachest.
I0226 17:41:22.055488       8 seachestprobe.go:186] Disk: /dev/nvme0n1p2 TemperatureDataValid:false filled by seachest.
I0226 17:41:22.055495       8 probe.go:107] details filled by seachest probe
E0226 17:41:22.055517       8 smartprobe.go:100] map[errorCheckingConditions:the device type is not supported yet, device type: "unknown"]
I0226 17:41:22.055525       8 probe.go:107] details filled by smart probe
E0226 17:41:22.055555       8 capacityprobe.go:96] unable to read sector sizeopen /sys/dev/block/259:2/queue/hw_sector_size: no such file or directory
I0226 17:41:22.055563       8 probe.go:107] details filled by capacity probe
```

**Comment by kmova** [comment]
Keep this open to merge this into master. This fix is included in https://github.com/openebs/node-disk-manager/pull/201 targeted for 0.4
